name: Terraform-Ansible Deployments

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Show Terraform Outputs
        run: |
          terraform -chdir=terraform output

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible jq

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/devops-key.pem
          chmod 400 ~/.ssh/devops-key.pem

      - name: Generate Dynamic Inventory
        run: |
          terraform -chdir=terraform output -json worker_ips > workers.json

          echo "Terraform Output:"
          cat workers.json

          jq -r '.[]' workers.json > worker_ips.txt

          echo "[webservers]" > ansible/inventory.ini

          COUNT=1

          while read -r IP; do
            echo "worker${COUNT} ansible_host=${IP}" >> ansible/inventory.ini
            COUNT=$((COUNT + 1))
          done < worker_ips.txt

          cat >> ansible/inventory.ini <<EOF

          [webservers:vars]
          ansible_user=ec2-user
          ansible_ssh_private_key_file=~/.ssh/devops-key.pem
          EOF

          echo "Generated Inventory:"
          cat ansible/inventory.ini

      - name: Test Ansible Connectivity
        run: |
          ansible all \
            -i ansible/inventory.ini \
            -m ping

      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/playbook.yml